# Define the image argument and provide a default value
ARG IMAGE=python:3-slim-bookworm

# Use the image as specified
FROM ${IMAGE}

# Re-declare the ARG after FROM
ARG IMAGE

# Update and upgrade the existing packages 
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    ninja-build \
    libopenblas-dev \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/*

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install --upgrade pip pytest cmake scikit-build setuptools fastapi uvicorn sse-starlette pydantic-settings starlette-context

RUN pip install llama-cpp-python==0.2.77 --verbose;
# Set environment variable for the host

# RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install --user llama-cpp-python==0.2.77 \
#     --extra-index-url https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.79/llama_cpp_python-0.2.79-cp312-cp312-linux_i686.whl
#     --verbose;

# # Copy and setup entrypoint.sh
# RUN mkdir /app
# WORKDIR /app

# COPY entrypoint.sh /app/entrypoint.sh
# RUN chmod +x /app/entrypoint.sh

ENV HOST=0.0.0.0
ENV PORT=8000

# Set the entrypoint
#ENTRYPOINT ["/app/entrypoint.sh"]

# Expose the default port
EXPOSE 8000

#CMD ["python3", "-m", "llama_cpp.server" ]